export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL';
export const USER_SIGNOUT = 'USER_SIGNOUT';

export const USER_SIGNUP_REQUEST = 'USER_SIGNUP_REQUEST';
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
export const USER_SIGNUP_RESET = 'USER_SIGNUP_RESET';
export const USER_SIGNUP_FAIL = 'USER_SIGNUP_FAIL';

export const CART_ADD_VIDEO = 'CART_ADD_VIDEO';
export const CART_REMOVE_VIDEO= 'CART_REMOVE_VIDEO';
export const CART_EMPTY = 'CART_EMPTY';
//export const CART_SAVE_SHIPPING_ADDRESS = 'CART_SAVE_SHIPPING_ADDRESS';
//export const CART_SAVE_PAYMENT_METHOD = 'CART_SAVE_PAYMENT_METHOD';
